B-2-P2-master/B_2_P2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    # path('', TemplateView.as_view(template_name="index.html")),
    path("", views.main_list, name="main_list"),
    path('logout', LogoutView.as_view()),

    path('admin/', admin.site.urls),
    path('pawn/', include('pawn.urls')),
    path('questions/', include("questions.urls")), 
    path('users/', include('users.urls')), 
    path('communities/', include('communities.urls')), 
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

B-2-P2-master/pawn/urls.py
from django.conf.urls import url
from .views import MarkdownifyView, ImageUploadView
from django.urls import path

urlpatterns = [
    path('markdownify/', MarkdownifyView.as_view(), name='pawn_markdownify'),
    path('upload/', ImageUploadView.as_view(), name='pawn_upload')
]

B-2-P2-master/questions/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from . import views

urlpatterns = [
    path("", views.questions_list, name="questions_list"),
    path("ask/", views.questions_ask, name="questions_ask"),
    path("search/", views.questions_search, name="questions_search"),
    path("tags/<tag>", views.questions_tag, name="questions_tag"),
    path("category/<category>", views.questions_category, name="questions_category"),

    path("<pk>/<slug>", views.questions_detail, name="questions_detail"),
    path("<pk>/<slug>/update", views.questions_detail_update, name="questions_detail_update"),
    path("<pk>/<slug>/delete", views.questions_delete, name="questions_delete"),
    path("<pk>/<slug>/bookmark", views.questions_detail_bookmark, name="questions_detail_bookmark"),
    path("<pk>/<slug>/thumbsup", views.questions_detail_thumbsup, name="questions_detail_thumbsup"),
    path("<pk>/<slug>/thumbsdown", views.questions_detail_thumbsdown, name="questions_detail_thumbsdown"),
    path("<pk>/<slug>/<comment_pk>/pin", views.questions_detail_pin, name="questions_detail_pin"),
    path("<pk>/<slug>/<comment_pk>/upvote", views.questions_comment_upvote, name="questions_comment_upvote"),
    path("<pk>/<slug>/<comment_pk>/downvote", views.questions_comment_downvote, name="questions_comment_downvote"),
    path("<pk>/<slug>/<comment_pk>/edit", views.questions_comment_edit, name="questions_comment_edit"),
    path("<pk>/<slug>/<comment_pk>/delete", views.questions_comment_delete, name="questions_comment_delete"),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

B-2-P2-master/questions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from pawn.models import PawnField
from taggit.managers import TaggableManager
from django.utils import timezone
from communities.models import Community

# for reverse lookup 
# https://docs.djangoproject.com/en/2.0/topics/db/queries/#related-objects

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=280)
    summary = models.TextField(max_length=380)
    slug = models.SlugField(max_length=480, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    tags = TaggableManager()

    solved = models.BooleanField(default=False)
    edited = models.BooleanField(default=False)

    thumbsup = models.ManyToManyField(User, blank=True, related_name='question_thumbsup')
    thumbsdown = models.ManyToManyField(User, blank=True, related_name='question_thumbsdown')

    viewed = models.ManyToManyField(User, blank=True, related_name='viewed')
    bookmark = models.ManyToManyField(User, blank=True, related_name='bookmark')

    noc = models.CharField(max_length=100, default="question")

    community = models.ForeignKey(Community, on_delete=models.CASCADE, blank=True, null=True)

    class Category(models.IntegerChoices):
        RANDOM = 0, "Random"
        MOVIE = 1, "Movie"
        MUSIC = 2, "Music"
        NEWS = 3, "News"
        CELEBRITY = 4, "Celebrity"
        TV_SHOWS = 5, "TV Shows"
        GAMES = 6, "Games"
        GENERAL = 7, "General"
        BUSINESS = 8, "Business"
        SPORTS = 9, "Sports"
        ACADEMIC = 10, "Academic"
        SOCIAL = 11, "Social"

    category = models.PositiveSmallIntegerField(
        choices=Category.choices,
        default=Category.RANDOM
    )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Question, self).save(*args, **kwargs)

    @property
    def get_vote(self):
        return str(self.thumbsup.count() - self.thumbsdown.count())

    @property
    def type(self):
        return "question"

    @property
    def get_time_delta(self):
        delta = timezone.now() - self.created_on
        seconds = delta.total_seconds()
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        seconds = int(seconds % 60)

        days = delta.days
        weeks = int(days // 4)
        months = int(days // 29.53)
        years = int(days // 365.25)

        if years > 0:
            if years == 1:
                return str(years) + " year ago"
            else:
                return str(years) + " years ago"

        if months > 0:
            if months == 1:
                return str(months) + " month ago"
            else:
                return str(months) + " months ago"

        if weeks > 0:
            if weeks == 1:
                return str(weeks) + " week ago"
            else:
                return str(weeks) + " weeks ago"
            
        if days > 0:
            if days == 1:
                return str(days) + " day ago"
            else:
                return str(days) + " days ago"

        if hours > 0:
            if hours == 1:
                return str(hours) + " hour ago"
            else:
                return str(hours) + " hours ago"

        if minutes > 0:
            if minutes == 1:
                return str(minutes) + " minute ago"
            else:
                return str(minutes) + " minutes ago"

        else:
                return str(seconds) + " seconds ago"

class QuestionComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    comment = PawnField()
    created_on = models.DateTimeField(auto_now_add=True)
    pinned = models.BooleanField(default=False)
    edited = models.BooleanField(default=False)

    upvote = models.ManyToManyField(User, blank=True, related_name='questioncomment_upvote')
    downvote = models.ManyToManyField(User, blank=True, related_name='questioncomment_downvote')

    def __str__(self):
        return self.question.title + "/" + self.user.username + "/" + str(self.id)

    @property
    def get_vote(self):
        vote = self.upvote.all().count() - self.downvote.all().count()
        return "{}".format(vote)

    @property
    def get_time_delta(self):
        delta = timezone.now() - self.created_on
        seconds = delta.total_seconds()
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        seconds = int(seconds % 60)

        days = delta.days
        weeks = int(days // 4)
        months = int(days // 29.53)
        years = int(days // 365.25)

        if years > 0:
            if years == 1:
                return str(years) + " year ago"
            else:
                return str(years) + " years ago"

        if months > 0:
            if months == 1:
                return str(months) + " month ago"
            else:
                return str(months) + " months ago"

        if weeks > 0:
            if weeks == 1:
                return str(weeks) + " week ago"
            else:
                return str(weeks) + " weeks ago"
            
        if days > 0:
            if days == 1:
                return str(days) + " day ago"
            else:
                return str(days) + " days ago"

        if hours > 0:
            if hours == 1:
                return str(hours) + " hour ago"
            else:
                return str(hours) + " hours ago"

        if minutes > 0:
            if minutes == 1:
                return str(minutes) + " minute ago"
            else:
                return str(minutes) + " minutes ago"

        else:
                return str(seconds) + " seconds ago"


class ReplyComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(QuestionComment, on_delete=models.CASCADE)
    reply = models.TextField(max_length=380)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + "/" + str(self.id)

    @property
    def get_time_delta(self):
        delta = timezone.now() - self.created_on
        seconds = delta.total_seconds()
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        seconds = int(seconds % 60)

        days = delta.days
        weeks = int(days // 4)
        months = int(days // 29.53)
        years = int(days // 365.25)

        if years > 0:
            if years == 1:
                return str(years) + " year ago"
            else:
                return str(years) + " years ago"

        if months > 0:
            if months == 1:
                return str(months) + " month ago"
            else:
                return str(months) + " months ago"

        if weeks > 0:
            if weeks == 1:
                return str(weeks) + " week ago"
            else:
                return str(weeks) + " weeks ago"
            
        if days > 0:
            if days == 1:
                return str(days) + " day ago"
            else:
                return str(days) + " days ago"

        if hours > 0:
            if hours == 1:
                return str(hours) + " hour ago"
            else:
                return str(hours) + " hours ago"

        if minutes > 0:
            if minutes == 1:
                return str(minutes) + " minute ago"
            else:
                return str(minutes) + " minutes ago"

        else:
                return str(seconds) + " seconds ago"

B-2-P2-master/questions/forms.py
from django import forms
from django.contrib.auth.models import User
from pawn.fields import PawnFormField
from .models import Question, QuestionComment, ReplyComment
from taggit.forms import TagWidget

class QuestionForm(forms.ModelForm):

    title = forms.CharField(
        max_length=280, 
        required=True, 
        widget=forms.TextInput(
            attrs={
                'class': 'text-control',
                'id': 'title', 
                "aria-describedby":"titleHelp",
                "autocomplete": "off",
                "oninput": "this.className = ''""",
            }
        ))

    summary = forms.CharField(
        max_length=380, 
        required=True, 
        widget=forms.Textarea(
            attrs={
                'class': 'text-control',
                'id': 'summary', 
                "aria-describedby":"summaryHelp",
                "autocomplete": "off",
                "oninput": "this.className = ''""",
            }
        ))

    class Meta:
        model = Question
        fields = ['title', 'tags', 'summary', 'category']

class QuestionUpdateForm(forms.ModelForm):
    summary = forms.CharField(
        max_length=380, 
        required=True, 
        widget=forms.Textarea(
            attrs={
                'class': 'text-control',
                'id': 'summary', 
                "aria-describedby":"summaryHelp",
                "autocomplete": "off",
                "rows": "3",
                "oninput": "this.className = ''""",
            }
        ))

    class Meta:
        model = Question
        fields = ['summary']

class QuestionCommentForm(forms.ModelForm):
    comment = PawnFormField()

    class Meta:
        model = QuestionComment
        fields = ['comment']
        widgets= {
            'tags' : TagWidget(attrs={'class':'text-control'}),
        }

class ReplyCommentForm(forms.ModelForm):
    reply = forms.CharField(
        max_length=380, 
        required=True, 
        widget=forms.Textarea(
            attrs={
                'class': 'text-control',
                'id': 'reply', 
                "aria-describedby":"replyHelp",
                "autocomplete": "off",
                "rows": "3",
                "oninput": "this.className = ''""",
            }
        ))

    class Meta:
        model = ReplyComment
        fields = ['reply']

class QuestionCommentEditForm(forms.ModelForm):
    comment = PawnFormField()

    class Meta:
        model = QuestionComment
        fields = ['comment']
        

B-2-P2-master/questions/templates/questions_ask.html
{% extends "base_ask.html" %}
{% load static %}

{% block css %}
<style>
    html,
    body {
        background-color: white;
    }
</style>
{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function (e) {
        $("#id_tags").css("width", "100%")
    })
</script>
<script defer src="{% static '/js/text-control-question.js' %}" type="text/javascript"></script>
<script async src="{% static '/js/pawn-questions-ask.js' %}" type="text/javascript"></script>
<script async src="{% static '/js/textarea-control.js' %}" type="text/javascript"></script>
<script> function Z29iYWNr(){window.history.back()} </script>
{% endblock %}

{% block content %}
<main style="width: 100%; padding: 20px 10px;">
    <form method="POST" name="pawnForm" enctype="multiple/form-data">
        <div style="display: flex; flex-direction:row;gap: 10px; margin: 10px 0;">
            <button onclick="Z29iYWNr()" style="text-align:center" class="a button button-danger">
                Cancel
            </button>
            <button style="display: flex; flex-direction: row; align-items:center; gap:7px;" name="_ask"
                class="button button-primary" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-question-lg" viewBox="0 0 16 16">
                    <path
                        d="M3 4.075a.423.423 0 0 0 .43.44H4.9c.247 0 .442-.2.475-.445.159-1.17.962-2.022 2.393-2.022 1.222 0 2.342.611 2.342 2.082 0 1.132-.668 1.652-1.72 2.444-1.2.872-2.15 1.89-2.082 3.542l.005.386c.003.244.202.44.446.44h1.445c.247 0 .446-.2.446-.446v-.188c0-1.278.487-1.652 1.8-2.647 1.086-.826 2.217-1.743 2.217-3.667C12.667 1.301 10.393 0 7.903 0 5.645 0 3.17 1.053 3.001 4.075zm2.776 10.273c0 .95.758 1.652 1.8 1.652 1.085 0 1.832-.702 1.832-1.652 0-.985-.747-1.675-1.833-1.675-1.04 0-1.799.69-1.799 1.675z" />
                </svg>
                Ask
            </button>
        </div>
        {% csrf_token %}

        <h2> Category </h2>
        {{form.category}}

        <h2> Title </h2>
        {{form.title}}

        <h2> Summary </h2>
        {{form.summary}}

        <h2> Tags </h2>
        {{form.tags}}

    </form>
</main>
{% endblock %}

B-2-P2-master/questions/templates/questions_category.html
{% extends "base_tags.html" %}
{% load static %}

{% block css %}
{% endblock %}

{% block javascript %}
<script async src="{% static '/js/bookmark.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<main class="main" style="width: 100%; padding: 20px 10px;">
    <h1> Category: {{category}} </h1>
    <div class="list infinite-container">
        {% for question in questions%}
        <div class="card infinite-item">
            <div class="card-header">
                <div class="card-header-item">
                    <div class="card-header-item-group">
                        <a href="{% url 'users_detail' pk=question.user.profile.pk username=question.user.username%}">
                            <img width="32px" height="32px" src={{question.user.profile.image.url}} />
                        </a>
                        <div>
                            <div class="item-name">
                                {% ifequal question.noc "community"%}
                                <div>
                                    From
                                    <strong>
                                        <a class="a"
                                            href="{% url 'communities_detail' pk=question.community.pk slug=question.community.slug%}">
                                            {{question.community.community_name}}
                                        </a>
                                    </strong>
                                    by
                                    <strong>
                                        <a class="a"
                                            href="{% url 'users_detail' pk=question.user.profile.pk username=question.user.username%}">
                                            {{question.user.username}}
                                        </a>
                                    </strong>
                                </div>
                                {% else %}
                                <a class="a"
                                    href="{% url 'users_detail' pk=question.user.profile.pk username=question.user.username%}">
                                    {{question.user.username}}
                                </a>
                                {% endifequal %}
                            </div>
                            <div class="item-date">
                                {{question.get_time_delta}} {% if question.edited %}(edited){%endif%}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <a class="a" href="{% url 'questions_detail' pk=question.pk slug=question.slug %}">
                    <div class="card-body-title">
                        {% if question.solved %}[STAR] {%endif%}{{question.title}}
                    </div>
                </a>
                <div class="card-body-summary">
                    {{question.summary|truncatewords:50}}
                </div>
                <div class="card-body-tags">
                    <a href="{% url 'questions_category' category=question.category%}" class="a tags-category">
                        {{question.get_category_display}} </a>
                    {% for tag in question.tags.all %}
                    <a class="a" href="{% url 'questions_tag' tag=tag%}"> {{tag}} </a>
                    {% endfor %}
                </div>
            </div>
            <div class="card-footer">
                <div class="card-footer-item">
                    <div class="card-footer-item-group">
                        <div class="card-footer-item-group-detail">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fd702e"
                                class="bi bi-eye-fill" viewBox="0 0 16 16">
                                <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                                <path
                                    d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                            </svg>
                            <div>
                                {{question.viewed.all.count}}
                            </div>
                        </div>
                        <div class="card-footer-item-group-detail">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fd702e"
                                class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                <path
                                    d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z" />
                            </svg>
                            <div>
                                {{question.thumbsup.all.count}}
                            </div>
                        </div>
                        <div class="card-footer-item-group-detail">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fd702e"
                                class="bi bi-chat-square-text" viewBox="0 0 16 16">
                                <path
                                    d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                                <path
                                    d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
                            </svg>
                            <div>
                                {{question.questioncomment_set.all.count}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer-item">
                    <div class="card-footer-item-group">
                        <form id="{{question.id}}" method="POST"
                            action="{% url 'questions_detail_bookmark' pk=question.pk slug=question.slug%}">
                            {% csrf_token %}
                            <button style="padding: 0; margin-right: 15px;"
                                class="question_detail_bookmark_button button" type="submit">
                                {% if user in question.bookmark.all%}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fd702e"
                                    class="bi {{question.pk}}-bi-bookmark-check-fill" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                        d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5zm8.854-9.646a.5.5 0 0 0-.708-.708L7.5 7.793 6.354 6.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z" />
                                </svg>
                                <svg style="display: none;" xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                    fill="#fd702e" class="bi {{question.pk}}-bi-bookmark" viewBox="0 0 16 16">
                                    <path
                                        d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z" />
                                </svg>
                                {% else %}
                                <svg style="display: none;" xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                    fill="#fd702e" class="bi {{question.pk}}-bi-bookmark-check-fill"
                                    viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                        d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5zm8.854-9.646a.5.5 0 0 0-.708-.708L7.5 7.793 6.354 6.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z" />
                                </svg>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fd702e"
                                    class="bi {{question.pk}}-bi-bookmark" viewBox="0 0 16 16">
                                    <path
                                        d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z" />
                                </svg>
                                {% endif %}
                            </button>
                        </form>

                        <button style="padding: 0;" class="button">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fd702e"
                                class="bi bi-share-fill" viewBox="0 0 16 16">
                                <path
                                    d="M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5z" />
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% if questions.has_next %}
    <div style="text-align: center;">
        <a class="infinite-more-link button button-primary" href="?page={{ questions.next_page_number }}">Load More</a>
    </div>
    {% endif %}

    <div class="loading" style="display: none;">
        Loading...
    </div>

</main>
{% endblock %}

B-2-P2-master/questions/templates/questions_update.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<style>
    html,
    body {
        background-color: white;
    }
</style>
{% endblock %}

{% block javascript %}
<script async src="{% static '/js/textarea-control.js' %}" type="text/javascript"></script>
<script async src="{% static '/js/text-control-question.js' %}" type="text/javascript"></script>
<script async src="{% static '/js/search.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div id="askModal" class="modal">
    <div class="modal-content">
        <form id="askForm" method="POST">
            {% csrf_token %}
            <div class="tab">
                <h1>Search Question
                    <span class="close">&times;</span>
                </h1>

                <p>Question
                    {{formQuestion.title}}</p>
                <div style="max-height: 200px; overflow-y: auto" id="searchResult">
                    <div id="searching"> Searching.. </div>
                </div>
            </div>

            <div class="tab">
                <p>Category
                    {{formQuestion.category}}
                </p>
                <p> Summarize it
                    {{formQuestion.summary}}
                </p>
            </div>

            <div class="tab">Tags
                <p>{{ formQuestion.tags }}</p>
            </div>

            <div style="overflow:auto;">
                <div style="float:right;">
                    <input name='_question' type="hidden">
                    <button class="button button-danger" type="button" id="prevBtn"
                        onclick="nextPrev(-1)">Previous</button>
                    <button class="button button-primary" type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
                </div>
            </div>

            <div style="text-align:center;margin-top:20px;">
                <span class="step"></span>
                <span class="step"></span>
                <span class="step"></span>
            </div>

        </form>
    </div>
</div>

<main style="width: 100%; padding: 0 10px;">
    <h2> Q: {{question.title}} </h2>
    <form method="POST" name="pawnForm" enctype="multiple/form-data">
        <div style="display: flex; flex-direction:row;gap: 10px; margin: 10px 0;">
            <a href="{% url 'questions_detail' pk=question.pk slug=question.slug %}" style="text-align:center"
                class="a button button-danger" type="button"> Cancel
            </a>
            <button style="display: flex; flex-direction: row; align-items:center; gap:7px;" name="_update"
                class="button button-primary" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-arrow-repeat" viewBox="0 0 16 16">
                    <path
                        d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41zm-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9z" />
                    <path fill-rule="evenodd"
                        d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5.002 5.002 0 0 0 8 3zM3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9H3.1z" />
                </svg>
                Update
            </button>
        </div>
        {% csrf_token %}

        {{form.summary}}

    </form>
</main>
{% endblock %}